#!/usr/bin/bash
## Usage: startwin [optional: path to live cdrom image]
## I have a  Windows 7 VM I run for work-related purposes. 
IMG_PATH=""
RAM_AMT="1657" ## in megabytes. (megabytes = gigabytes * 1024)
MACHINE="q35" # run qemu -machine help for list of supported machine types on your system
ENABLE_KVM="-enable-kvm" ##  comment out this line, or better, set to an empty string, to disable kvm
QEMU_ARGS=" -hda ${IMG_PATH} -m ${RAM_AMT} -machine ${MACHINE} ${ENABLE_KVM}"

if [[ ! "$1" == "" ]]
then
	echo "detected a command-line argument, assuming it is a cdrom file to boot."
  QEMU_ARGS="-boot once=d -cdrom ${CDROM_PATH} ${QEMU_ARGS}"
fi

/usr/bin/nice -10 /usr/bin/qemu-system-x86_64 ${QEMU_ARGS}
